# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='header_text_color',
            field=models.CharField(default='#363636', max_length=50),
            preserve_default=False,
        ),
    ]
